battery/views.py
from battery.models import db, User, Entry, Comment
from flask import render_template, request, session, flash, redirect, url_for
from flask import g, jsonify, abort, Blueprint, current_app, send_file
from functools import wraps
from sqlalchemy.exc import IntegrityError
from werkzeug.utils import secure_filename
from datetime import datetime
from imghdr import test_png, test_jpeg, test_bmp, test_gif
from calendar import monthrange
from collections import defaultdict
import os

# There is no merit to use blueprint now
# I just don't want views.py depend on specific app object
bp = Blueprint("app", __name__)

def login_required(fn):
    @wraps(fn)
    def decorated_view(*args, **kwargs):
        if g.user is None:
            flash("You must log in first", "error")
            return redirect(url_for("app.login", next=request.path))
        return fn(*args, **kwargs)
    return decorated_view

@bp.before_request
def load_user():
    user_id = session.get("user_id")
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(session["user_id"])

@bp.route("/")
def index():
    entries = Entry.query.order_by(Entry.created_at.desc()).all()
    return render_template("index.html", entries=entries)

@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")

    username = request.form["username"]
    password = request.form["password"]
    
    if not username or not password:
        flash("Username or password is empty", "error")
        return render_template("login.html")

    user, authenticated = User.authenticate(db.session.query,
                                            request.form["username"],
                                            request.form["password"])
    if authenticated:
        session["user_id"] = user.id
        flash("You were logged in", "info")
        return redirect(url_for("app.index"))
    else:
        flash("Invalid username or password", "error")
        return render_template("login.html")

@bp.route("/logout")
def logout():
    session.pop("user_id", None)
    flash("You were logged out", "info")
    return redirect(url_for("app.index"))

@bp.route("/entry/new/", methods=["GET", "POST"])
@login_required
def post_entry():
    if request.method == "GET":
        return render_template("editor.html", destination=url_for("app.post_entry"))

    title = request.form["title"]
    content = request.form["content"]
    save_as_draft = request.form.get("save-as-draft", False)

    if not title:
        flash("Title is empty", "error")
        return render_template("editor.html",
                               content=content,
                               destination=url_for("app.post_entry"))

    entry = Entry(title=request.form["title"],
                  content=request.form["content"],
                  user_id=session["user_id"],
                  is_public=not save_as_draft)

    db.session.add(entry)
    db.session.commit()
    return redirect(url_for("app.show_entry", entry_id=entry.id))

@bp.route("/entry/<int:entry_id>/edit/", methods=["GET", "POST"])
@login_required
def edit_entry(entry_id):
    entry = Entry.query.get(entry_id)

    if entry is None:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))
    
    if g.user.id != entry.user_id:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    if request.method == "GET":
        return render_template("editor.html",
                               destination=url_for("app.edit_entry", entry_id=entry_id),
                               title=entry.title,
                               content=entry.content)

    title = request.form["title"]
    content = request.form["content"]
    save_as_draft = request.form.get("save-as-draft", False)

    if not title:
        flash("Title is empty", "error")
        return render_template("editor.html",
                               content=content,
                               destination=url_for("app.edit_entry", entry_id=entry_id))

    entry.title = request.form["title"]
    entry.content = request.form["content"]
    entry.is_public = not save_as_draft
    db.session.commit()

    return redirect(url_for("app.show_entry", entry_id=entry.id))

@bp.route("/entry/<int:entry_id>/")
def show_entry(entry_id):
    entry = Entry.query.get(entry_id)

    if entry is None:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    if not entry.is_public and (g.user is None or g.user.id != entry.user_id):
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    comments = Comment.query.filter_by(entry_id=entry_id)
    return render_template("entry.html", entry=entry, comments=comments)

@bp.route("/entry/<int:entry_id>/delete/")
@login_required
def delete_entry(entry_id):
    entry = Entry.query.get(entry_id)

    if entry is None:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    if g.user.id != entry.user_id:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    db.session.delete(entry)
    db.session.commit()
    return redirect(url_for("app.index"))

@bp.route("/entry/<int:entry_id>/comment/", methods=["POST"])
def post_comment(entry_id):
    author = request.form["author"]

    if not author:
        author = None

    comment = Comment(author=author,
                      content=request.form["content"],
                      entry_id=entry_id)
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for("app.show_entry", entry_id=entry_id))

@bp.route("/entry/<int:entry_id>/comment/<int:comment_id>/delete/")
@login_required
def delete_comment(entry_id, comment_id):
    entry = Entry.query.get(entry_id)

    if entry is None:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    if g.user.id != entry.user_id:
        flash("Entry not found", "error")
        return redirect(url_for("app.index"))

    comment = Comment.query.get(comment_id)

    if comment is None:
        flash("Comment not found", "error")
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for("app.show_entry", entry_id=entry_id))

@bp.route("/entry/search/")
def search_entries():
    q = request.args["q"]
    entries = Entry.query.filter(Entry.content.contains(q))
    return render_template("index.html", entries=entries)

@bp.route("/entry/preview/", methods=["POST"])
@login_required
def show_preview():
    title = request.form["title"]
    content = request.form["content"]
    return render_template("preview.html", title=title, content=content)


@bp.route("/data/<string:file_name>/", methods=["GET"])
def dowload_img(file_name):
    upload_dir = current_app.config["UPLOAD_DIR"]
    file_path = os.path.join(upload_dir, secure_filename(file_name))
    return send_file(file_path)

@bp.route("/data/upload/", methods=["GET", "POST"])
def upload_img():
    upload_dir = current_app.config["UPLOAD_DIR"]

    if request.method == "GET":
        files = os.listdir(upload_dir)
        return render_template("upload.html", files=files)

    file = request.files["file"]
    head = file.read(20)

    valid_type = False
    for test in (test_png, test_jpeg, test_bmp, test_gif):
        # I don't know whether the 2nd arg is valid or not.
        # these test function is defined at:
        #   https://hg.python.org/cpython/file/3.6/Lib/imghdr.py
        valid_type = valid_type or test(head, None)

    if not valid_type:
        flash("Invalid file type", "error")
    else:
        file_name = datetime.now().strftime("%Y%m%d_%H%M%S_") + secure_filename(file.filename)
        file.seek(0) # really need this?
        file.save(os.path.join(upload_dir, file_name))

    return redirect(url_for("app.upload_img"))

@bp.route("/data/delete/<string:file_name>/", methods=["GET"])
def delete_img(file_name):
    upload_dir = current_app.config["UPLOAD_DIR"]
    file_path = os.path.join(upload_dir, file_name)
    os.remove(file_path)
    return redirect(url_for("app.upload_img"))

@bp.route("/about/", methods=["GET"])
def about():
    return render_template("about.html")

def calc_archive_range(year, month=None, day=None):
    # set month range
    start_month = end_month = month
    if month is None:
        start_month = 1
        end_month = 12

    # set day range
    start_day = end_day = day
    if day is None:
        start_day = 1
        end_day = 31 if month is None else monthrange(year, month)[1]

    return (start_month, start_day, end_month, end_day)

@bp.route("/archive/", methods=["GET"])
def archive():
    entries = Entry.query.filter(Entry.is_public).order_by(Entry.created_at).all()

    if not entries:
      return render_template("archive.html", n_entries={})

    oldest_datetime = entries[0].created_at
    newest_datetime = entries[-1].created_at

    n_entries = defaultdict(lambda: [])
    for year in range(newest_datetime.year, oldest_datetime.year-1, -1):
        for month in range(12, 0, -1):
            start_day = 1
            _,end_day = monthrange(year, month)

            start_datetime = datetime(year, month, start_day, 0, 0, 0, 0)
            end_datetime = datetime(year, month, end_day, 23, 59, 59, 999)

            n = Entry.query.filter(start_datetime <= Entry.created_at,
                                   Entry.created_at <= end_datetime).count()

            if n == 0:
                continue

            n_entries[year].append((month, n))
    return render_template("archive.html", n_entries=n_entries)

@bp.route("/archive/<int:year>/<int:month>/<int:day>", methods=["GET"])
@bp.route("/archive/<int:year>/<int:month>", methods=["GET"])
@bp.route("/archive/<int:year>/", methods=["GET"])
def archive_with_datetime(year, month=None, day=None):

battery/templates/about.html
{% extends "base.html" %}
{% block body %}
{% endblock %}

battery/templates/archive.html
{% extends "base.html" %}
{% block body %}
<h1>Monthly Archive</h1>
{% for year, months in n_entries.items() %}
<div class="archive-year">
  <i class="fas fa-angle-right angle" id="angle-{{year}}" onclick="toggle_archive_list({{year}});"></i>
  <div class="archive-year-label">{{year}}</div>
  <ul class="archive-list" id="archive-list-{{year}}" style="display:none;">
    {% for month, n in months %}
    <li><a href="/archive/{{year}}/{{month}}">{{year}} / {{month}} ({{n}})</a></li>
    {% endfor %}
  </ul>
</div>
{% endfor %}
{% endblock %}

battery/templates/base.html
{% extends "meta.html" %}
{% block container %}
<!-- Sign in link -->
<nav class="toolbar">
  <ul>
    {% if session.user_id %}
    <li><a href="{{ url_for('app.post_entry') }}">New entry</a></li>
    <li><a target="_blank" href="{{ url_for('app.upload_img') }}">Upload</a></li>
    <li><a href="{{ url_for('app.logout') }}">Log out</a></li>
    <li>({{ g.user.username }})</li>
    {% endif %}
  </ul>
</nav>

<header>
  <!-- Logo -->
  <div class="logo">
    <a href="/">
      <img src="{{ url_for('static', filename='img/logo.png') }}">
    </a>
  </div>
</header>

{% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="flash-{{category}}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

<nav class="navbar">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about/">About</a></li>
    <li><a href="/archive/">Archive</a></li>
    <li>
      <form action="{{ url_for('app.search_entries') }}" method="get" class="search-box">
        <input type="text" placeholder="Keyword" name="q">
        <input type="submit" value="Search">
      </form>
    </li>
  </ul>
</nav>

{% block body %}{% endblock %}

<footer>
  <p class="copyright">
  © Copyright 2018 d2verb.
  </p>
</footer>

{% endblock %}

battery/templates/editor.html
{% extends "base.html" %}
{% block body %}
<form action="{{ destination }}" name="editor" method="post" class="editor">
  <label for="title">Title</label>
  <input type="text" name="title" placeholder="Title" value="{{ title }}">
  <label for="content">Content</label>
  <textarea name="content" placeholder="Content">{{ content }}</textarea>
  <input type="checkbox" name="save-as-draft" id="save-as-draft">
  <label for="save-as-draft">Save as draft</label>
  <br>
  <input type="button" value="Preview" onclick="open_preview_window()">
  <input type="submit" value="Post">
</form>
{% endblock %}

battery/templates/entry.html
{% extends "base.html" %}
{% block body %}
<article>
  <div class="title">
    <h1>
      <a href="{{ url_for('app.show_entry', entry_id=entry.id) }}">
        {{ entry.title }}
      </a>
    </h1>
  </div>

  <div class="byline">
    <i class="far fa-clock"></i>
    <time>{{ entry.created_at }}</time>
    <i class="fas fa-user"></i>
    <span class="author">{{ get_username(entry.user_id) }}</span>
    {% if not entry.is_public and entry.user_id == session.user_id %}
    <i class="fas fa-user-secret" id="draft-icon"></i>
    {% endif %}

    {% if entry.user_id == session.user_id %}
    <a class="edit" href="{{ url_for('app.edit_entry', entry_id=entry.id) }}"><i class="far fa-edit"></i></a>
    <a class="delete" href="{{ url_for('app.delete_entry', entry_id=entry.id) }}"><i class="far fa-trash-alt"></i></a>
    {% endif %}
  </div>


  <div class="content">
    {{ markdown_to_html(entry.content) | safe }}
  </div>

  <div class="comments">
    <h3>Leave your comment</h3>
    <form action="{{ url_for('app.post_comment', entry_id=entry.id) }}" method="post">
      <label for="author">Your name</label>
      <input type="text" name="author" placeholder="Your name">
      <label for="content">Comment</label>
      <textarea name="content" placeholder="Comment"></textarea>
      <input type="submit" value="Submit">
    </form>

    <h3>Comments</h3>
    {% for comment in comments %}
    <div class="comment">
      <div class="author">{{ comment.author }}</div>
      <p class="content">
      {{ comment.content }}
      </p>

      <div class="menu">
        <ul>
          <li>{{ entry.created_at }}</li>
          {% if entry.user_id == session["user_id"] %}
          |
          <li>
            <!--
            <a href="{{ url_for('app.delete_comment', entry_id=entry.id, comment_id=comment.id) }}">delete</a>
            -->
            <a class="delete" href="{{ url_for('app.delete_comment', entry_id=entry.id, comment_id=comment.id) }}"><i class="far fa-trash-alt"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% endfor %}
  </div>
</article>
{% endblock %}

battery/templates/index.html
{% extends "base.html" %}
{% block body %}
{% for entry in entries %}
{% if entry.is_public or entry.user_id == session.user_id %}
<article>
  <div class="title">
    <h1>
      <a href="{{ url_for('app.show_entry', entry_id=entry.id) }}">
        {{ entry.title }}
      </a>
    </h1>

  </div>
  <div class="byline">
    <i class="far fa-clock"></i>
    <time datetime={{entry.created_at}}>{{ entry.created_at }}</time>
    <i class="fas fa-user"></i>
    <span class="author">{{ get_username(entry.user_id) }}</span>
    {% if not entry.is_public %}
    <i class="fas fa-user-secret" id="draft-icon"></i>
    {% endif %}

    {% if entry.user_id == session.user_id %}
    <a class="edit" href="{{ url_for('app.edit_entry', entry_id=entry.id) }}"><i class="far fa-edit"></i></a>
    <a class="delete" href="{{ url_for('app.delete_entry', entry_id=entry.id) }}"><i class="far fa-trash-alt"></i></a>
    {% endif %}
  </div>
</article>
{% endif %}
{% endfor %}
{% endblock %}

battery/templates/login.html
{% extends "base.html" %}
{% block body %}
<form action="{{ url_for("app.login") }}" method="post" class="login-form">
  <label for="username">Username</label>
  <input type="text" name="username" placeholder="Username">
  <label for="password">Password</label>
  <input type="password" name="password" placeholder="Password">
  <input type="submit" value="Log in">
</form>
{% endblock %}

battery/templates/meta.html
<!doctype html>
<html>
  <head>
    <title>Battery</title>
    <meta charset=utf-8>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class=container>
      {% block container %} {% endblock %}
    </div>
    <script text="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
  </body>
</html>

battery/templates/preview.html
{% extends "meta.html" %}
{% block container %}
<article>
  <div class="title">
    <h1>{{ title }}</h1>
  </div>

  <div class="byline">
    <i class="far fa-clock"></i>
    <time>YYYY-MM-DD</time>
    <i class="fas fa-user"></i>
    <span class="author">{{ get_username(session.user_id) }}</span>
  </div>


  <div class="content">
    {{ markdown_to_html(content) | safe }}
  </div>

</article>
{% endblock %}

battery/templates/upload.html
{% extends "meta.html" %}
{% block container %}
<h1>Upload an image file</h1>

{% for message in get_flashed_messages() %}                                            
<div class=flash>{{ message }}</div>
{% endfor %}

<p>You can upload small image file via this form.</p>

<form action="/data/upload/" method="post" name="uploader" class="uploader" enctype="multipart/form-data">
  <div class="file-selector">
    <input type="file" name="file">
    <p>Max size is 1MB per file</p>
  </div>
  <input type="submit" value="Upload">
</form>


<h1>Images</h1>
<hr>
<div class="file-list">
{% for file in files %}
  <div class="file-group">
    <a href="/data/{{file}}">
    <img src="/data/{{file}}" width=100px>
    </a>
    <a href="/data/delete/{{file}}">
    <button>Delete</button>
    </a>
  </div>
{% endfor %}
</div>

{% endblock %}